### ISSUE TITLE
请问，你的最新的config文件变成空的了？

### ISSUE THREAD

**Issue by youyoudeyou** [HouCoder/asrock-z370m-pro4-hackintosh#1]

**Comment by HouCoder** [comment]
一直都是空的，这个板子黑苹果不需要太多额外的设置的，额外的不必要设置可能导致一些其它的问题哦，只需要注意 Audiu Inject 为 1，Devices / Properties 下面注入正确的 platform id 即可使用。

**Comment by youyoudeyou** [comment]
谢谢！搬你的clover试试！

**Comment by yyccbbz** [comment]
我已按照此EFI安装成功，遇到一个问题，就是开机读条的时候 有花屏

**Comment by HouCoder** [comment]
@yyccbbz 开机读条有花屏属于正常现象，我在升级到 10.14.5 的时候也遇到了轻微的花屏，只要不影响正常使用就好。
