### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by 876310253** [HouCoder/asrock-z370m-pro4-hackintosh#10]
大佬，我主板跟你一样，就cpu跟显卡不一样，我的cpu是i5-8600k  显卡是rx570，请问我可以直接套用你的config吗？如果不能，我需要修改哪些地方，求教。我之前自己弄过笔记本的黑苹果，第一次装台式机。对黑苹果算是有点了解。不是特别熟。

**Comment by HouCoder** [comment]
不能直接用，config-public.plist 需要先重命名成 `config.plist`，序列号也需要你自己生成，usb patch 不确定在你那里能不能正常使用
