### ISSUE TITLE
Update for Catalina 10.15.4 (Thank you, @HouCoder)

### ISSUE THREAD

**Issue by JeanMichelleJarre** [HouCoder/asrock-z370m-pro4-hackintosh#11]
https://github.com/JeanMichelleJarre/EFI-Hackintosh-Catalina-10.15.4-Asrock-z370m-pro4-OpenCore-0.5.4

**Comment by HouCoder** [comment]
Updated to 10.15.4 last night, now it's using OpenCore 0.5.7, enjoy.
