### ISSUE TITLE
USBs not working. 

### ISSUE THREAD

**Issue by JeanMichelleJarre** [HouCoder/asrock-z370m-pro4-hackintosh#12]
Hello! Sorry for the inconvenience but I wanted to ask you a question. First of all, thank you for your work! I have been testing this OC 0.5.7 but I have a problem, USB is not working.
I have seen that you put "2.- Do not use OC / Kexts / USBPorts.kext."
If I remove that kext (or replace it with USBInjectAll.kext) the PC won't start. I do not understand why this happens since with the other versions all the USBs work perfectly.
Thanks again for your work. Regards.

**Comment by HouCoder** [comment]
I suggest you make a USB port patch for your system. https://www.tonymacx86.com/threads/the-new-beginners-guide-to-usb-port-configuration.286553/
