### ISSUE TITLE
请问下能看到风扇转速吗？

### ISSUE THREAD

**Issue by webleon** [HouCoder/asrock-z370m-pro4-hackintosh#14]
这块主板的LPC不太常见，目前正在用Clover引导，用FakeSMC和VirtualSMC都无法侦测风扇转速。

请加一下，你改成OC以后，是否可以支持监测风扇转速？

**Comment by HouCoder** [comment]
我没注意过风扇转速的问题，感觉挺安静的，从 Intel Power Gadget 里面看日常使用 CPU 温度在 40 度左右。你是用什么软件看的？我也整一个看看能不能看到。

**Comment by webleon** [comment]
感谢回复。
我用的是 HWMonitor，或者 App Store 里面的 iStat Menus
https://github.com/CloverHackyColor/HWMonitorSMC2
https://apps.apple.com/cn/app/istat-menus/id1319778037?mt=12

目前风扇调速本身没有问题，只是传感器看不到转速。

**Comment by HouCoder** [comment]
刚试了下，我这里也看不到，我以前还没注意过这一块，我平时不用设备监控软件，DIY 的黑苹果散热给力，基本上没遇到过 CPU 温度过 50 度的时候，还是挺安静的。

**Comment by liangyimingcom** [comment]
我用的是 HWMonitor，这个好用，谢谢。
https://github.com/CloverHackyColor/HWMonitorSMC2
