### ISSUE TITLE
同主板ssdt-plug的问题

### ISSUE THREAD

**Issue by fgy58963** [HouCoder/asrock-z370m-pro4-hackintosh#17]
Hi，我正准备从Z390 Aorus Pro切换到Z370M Pro4。我使用的CPU是9900K，请问SSDT-PLUG需要重新去Windows取值然后做修改么？我现在Z390用的SSDT-PLUG如下：

//
// Leverages the PMPM approach found in https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/AcpiSamples/SSDT-PLUG.dsl
//
DefinitionBlock ("", "SSDT", 2, "CORP", "CpuPlug", 0x00003000)
{
    External (\_SB.PR00, ProcessorObj)
    Method (PMPM, 4, NotSerialized) {
       If (LEqual (Arg2, Zero)) {
           Return (Buffer (One) { 0x03 })
       }
       Return (Package (0x02)
       {
           "plugin-type", 
           One
       })
    }
    Scope (\_SB.PR00)
    {
        If (_OSI ("Darwin")) {
            Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
            {
                Return (PMPM (Arg0, Arg1, Arg2, Arg3))
            }
        }
    }
}

**Comment by HouCoder** [comment]
> 请问SSDT-PLUG需要重新去Windows取值然后做修改么？

取决于 CPU 的 scope 和 id 有没有变。

参考下这个文章 - https://dortania.github.io/Getting-Started-With-ACPI/Universal/plug-methods/manual.html，其实很简单，你可以看下我的 https://github.com/HouCoder/asrock-z370m-pro4-hackintosh/blob/master/OC/ACPI/SSDT-PLUG.dsl，我的 scope 是 _PR，CPU ID 是 PR00，你对应着改就好了。
