### ISSUE TITLE
关于CPU

### ISSUE THREAD

**Issue by Billmvp73** [HouCoder/asrock-z370m-pro4-hackintosh#2]
想请教一下，有关装黑苹果CPU的问题，有些论坛说Intel core的都可以，tonymacx86上只推荐了一些，我有点想买i5 9400f，但是tonymacx86上并没有推荐，大佬看看可以吗

**Comment by HouCoder** [comment]
i5 9400f 是可以的，f 系列的只是没有集成显卡，需要自己搭配显卡。

https://www.reddit.com/r/hackintosh/comments/ax3rcl/successful_mojave_build/
