### ISSUE TITLE
显卡和蓝牙冲突

### ISSUE THREAD

**Issue by sommycasu** [HouCoder/asrock-z370m-pro4-hackintosh#3]
因为学习Flutter，想尝试下MacOS，所以把原有8600K+Z370m Pro+1066配置的显卡换了个HIS Rx580 4G，淘宝卖的挺多的，大多是矿卡，也挺便宜的，买回来成色什么的也不错，实际游戏比原来1066低20%左右，不过无所谓了。另外又入了个无线网卡BCM943602cs想尝试高级功能，于是就折腾起来。自从换了580，升级到了Mojave,忽略了网卡蓝牙测试，最近才发现怎么折腾蓝牙都不稳定，win系统下直接无法识别硬件，macOS下偶尔能识别，但功能也无法使用，无法搜索到任何蓝牙设备。刚开始以为是网卡问题，商家又发来一个还不行。于是开始测试下硬件兼容，发现拔掉RX580的情况下，可以正确识别网卡和蓝牙，功能也没任何问题，插上独显后，无线网卡功能没有问题，但是蓝牙设备直接变为另一个设备，而且也不能加载任何驱动，win和mac下都如此。可以明确是显卡和网卡蓝牙冲突。但显卡本身的表现是没有任何问题的，太奇怪了。

**Comment by HouCoder** [comment]
BCM943602cs 的蓝牙在 Windows 下是不可用的，我这里也遇到过同样的问题，至于冲突的问题你可以参考着教程做一个 USB 补丁试试？我的蓝牙在 macOS 下面工作是正常的。

**Comment by sommycasu** [comment]
感谢回复，蓝牙本身，我测试了核显和n卡下都可以正常驱动，使用也没问题，唯独在rx580下面有问题，而且找了个哥们换了主板测试没问题。问了下华擎技术支持，也没见过这样的情况。其中有个情况是，我把580显卡拆下，过段时间装回，首次开机蓝牙大概率没问题，过段时间再打开电脑就又识别不了蓝牙了。

**Comment by HouCoder** [comment]
显卡的问题？试试和淘宝卖家商量换换？

**Comment by HouCoder** [comment]
建议使用蓝宝石的显卡，从经验上来看对黑苹果的支持是最好的，如果不玩游戏的话买个 RX 560 应该是够了，价格也不贵，淘宝 300 左右，当然也是矿卡。

**Comment by sommycasu** [comment]
今天跟淘宝商家商量了下，把his的退了，再入个蓝宝588白金版试试 lol

**Comment by HouCoder** [comment]
> 今天跟淘宝商家商量了下，把his的退了，再入个蓝宝588白金版试试 lol

注意去网上搜索下有没有兼容性问题再买，蓝宝石的也不是每张卡都兼容的
