### ISSUE TITLE
Please go to https://panic.apple.com to report this panic

### ISSUE THREAD

**Issue by qxuan512** [HouCoder/asrock-z370m-pro4-hackintosh#5]
Please go to https://panic.apple.com to report this panic
您好，我主板和您的一样，用了黑果小兵的镜像直接安装完成，进入系统会出现上述错误，换成您的efi，进入系统进度条不动，不知道您知道问题在哪

**Comment by HouCoder** [comment]
我不清楚黑苹果小兵的镜像，你最好使用官方的原版镜像来安装，还有 Please go to https://panic.apple.com to report this panic 是完全没有用的，你仔细看看错误信息，贴一下有用的信息。
