### ISSUE TITLE
Opencore?

### ISSUE THREAD

**Issue by carlosxfigueroa** [HouCoder/asrock-z370m-pro4-hackintosh#6]
hello, any plans on migrating to opencore? currently upgraded to catalina with the same specs you have and the only issue so far is random freezing ( I assume due to clover)

**Comment by HouCoder** [comment]
Would you like to post the kernel log of random freezing?

Currently I don't have enough time to learn and try opencore, I heard it's amazing, will try it out when I have time.

**Comment by carlosxfigueroa** [comment]
it didnt give me a log, but I did another clean install and it seems to have self corrected, and I tried opencore but didnt really understand it, hopefully we get it working because I heard clover isnt getting support in the future

**Comment by HouCoder** [comment]
Updated to Catalina last night, pretty stable.
