### ISSUE TITLE
Carbon Copy Cloner on 10.15.1 - Crash... 

### ISSUE THREAD

**Issue by JeanMichelleJarre** [HouCoder/asrock-z370m-pro4-hackintosh#7]
Hi. Thank you for your work!! I wanted to ask you a question. I have updated perfectly to 10.15.1 without any problem but Carbon Copy Cloner does not open and close automatically. It has also happened to me with another pair of computers with hackintosh. Do you also happen to you? Thank you. Regards.

**Comment by JeanMichelleJarre** [comment]
Process:               Carbon Copy Cloner [531]
Path:                  /Applications/Carbon Copy Cloner.app/Contents/MacOS/Carbon Copy Cloner
Identifier:            com.bombich.ccc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Carbon Copy Cloner [531]
User ID:               501

Date/Time:             2019-11-01 21:41:33.777 +0100
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12


Time Awake Since Boot: 200 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
-->
    __TEXT                 0000000105c28000-0000000105eb6000 [ 2616K] r-x/rwx SM=COW

Thread 0 Crashed:
0                                     0x000000010dffc000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee9fd7c40
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010dffc000  rfl: 0x0000000000000200  cr2: 0x0000000000000000

Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x105c28000 -        0x105eb5ff7 + (0) <03735D7C-8DBD-3308-9BEE-F94B6C6BF36C>
       0x10dffb000 -        0x10e08bb5f + (733.6) <DAFEA246-2F9A-3DCB-A37C-4246D4F92770>

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 112
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=3564K resident=0K(0%) swapped_out_or_unallocated=3564K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)

                                VIRTUAL   REGION
REGION TYPE                        SIZE    COUNT (non-coalesced)
===========                     =======  =======
STACK GUARD                       56.0M        1
Stack                             8192K        1
__DATA                             796K        3
__DATA_CONST                        20K        1
__LINKEDIT                         380K        3
__TEXT                            3196K        2
shared memory                        8K        2
===========                     =======  =======
TOTAL                             68.3M       13

Model: iMac19,1, BootROM 220.270.93.0.0, 6 processors, 6-Core Intel Core i5, 3,2 GHz, 16 GB, SMC 2.46f12
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Memory Module: BANK 0/DIMM1, 8 GB, DDR4, 3000 MHz, Kingston, KHX2666C168G
Memory Module: BANK 1/DIMM1, 8 GB, DDR4, 3000 MHz, Kingston, KHX2666C168G
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.106.3 AirPortDriverBrcmNIC-1435.3)
Bluetooth: Version 7.0.1f1, 3 services, 25 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
USB Device: USB 3.0 Bus
USB Device: USB Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus:

**Comment by HouCoder** [comment]
It works fine for me, no issue, could you try to update to the latest version?

**Comment by JeanMichelleJarre** [comment]
Yes, indeed with the legal version downloaded from the page, it does work. 
The latest version of the "less legal" versions is the one that failed.
Thanks. Regards!
