### ISSUE TITLE
同主板使用了你的OC配置 并且自己生成了Generic信息开机报错

### ISSUE THREAD

**Issue by wjswjw** [HouCoder/asrock-z370m-pro4-hackintosh#9]
开机提示 OC: Failed to load configuration

**Comment by JeanMichelleJarre** [comment]
Rename config-public.plist to config.plist

**Comment by wjswjw** [comment]
> 将config-public.plist重命名为config .plist

谢谢 真是太SB了 这么简单的问题也没想到
